# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c90f04f835e9fd17c2334d78fd70922709cd936025edc79bcf6f37863d304cd6a3f65e6f697fbbd457076626b0a77efbd849447fbc9e764ef58acfa871433892

test:
  secret_key_base: 097d8dbd37a6149a24a2da368f01fc967d302adf462be42d865cea571ea0dac44aa37576720956bb5c825af38e262c553961d0262a9e1bb2d4f6711fb303d40e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
